### ISSUE TITLE
Codacy Code Style Issue: Missing docstring in __init__

### ISSUE THREAD

**Issue by fms528** [PRIS2/gamma#2]

**Comment by DiegoCangas** [comment]
No esta claro cual es el problema, ¿puedes especificarlo más para que pueda corregirlo?

**Comment by fms528** [comment]
Con los cambios que has hecho el issue debería haber desaparecido, aunque no la haya hecho, pues veo que has incluido un docstring al método __init__, con una descripción de lo que hace. Yo creo que se puede cerrar este issue.

**Comment by fms528** [comment]
Justo después del comentario anterior, codacy se ha actualizado. Ahora hay dos nuevos issues, pero este se ha solucionado.

**Comment by DiegoCangas** [comment]
Si justo estaba haciendo cambios, ya está todo solucionado.
Gracias, Un saludo
